### ISSUE TITLE
Error in console "observer is not a function" while scroll & draggable props is false

### ISSUE THREAD

**Issue by erastian** [Yhk5306/kotix-carousel#1]
Hey!

I found that error while I played with your code. Its easy to fix. You define observer like variable and define their behavior when proceeding props, but in cases when scroll & draggable props is false observer stays just a empty var. And after that you call it in onMounted block. That call in onMounted is what causes the Error in console.

Just add in `if (props.scroll && !props.draggable){}` (line 173 in KotixSection.vue) function else block with define for example an empty function like this
`if (props.scroll && !props.draggable){
...
} else {
observer = () => {}
}`
 and error will disappear.
 
 Thanks)))

**Comment by erastian** [comment]
or for example do not call observer in onMounted while scroll & draggable props is false :)

**Comment by Yhk5306** [comment]
Thank you for your recommendation. I will fix it ASAP :)
